name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !(contains(github.event.head_commit.message, 'chore(release):') || contains(github.event.head_commit.message, 'chore(deps'))
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install development dependencies
        run: |
          poetry install --only dev

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
